### ISSUE TITLE
description.yaml updates

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#11]
Necessary to have machine-interpretable flags for preprocessor arguments:

- How can I identify which file is a bed-file that will produce input DNA sequence, e.g.:
description.yaml:
```
...
data_preprocessor:
    function_name: extractor
    type: generator
    arguments:
        intervals_file: "string; tsv file with `chrom start end`; DNA_regions:bed3"
...
```
This can then be parsed looking for e.g. "DNA_regions:" + a format "bed3"
