### ISSUE TITLE
Setup configuration management in `~/.kipoi/config.yml`

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#16]
## `config.yml` file

```yaml
- kipoi_models_path: `~/.kipoi/models` # path to the kipoi models
- other_models_path: # a list, empty by default
  - ~/local_dir1
  - ~/local_dir2/
```

Reading config in Keras: https://github.com/fchollet/keras/blob/6f3e6bb6fc97e706f37dc078ae821f490b78035b/keras/backend/__init__.py#L14-L43
