### ISSUE TITLE
conda: keep `::` in specifying the channel per model

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#293]
Conda fixed in April the usage of the following format:

```yaml
name: test-env
dependencies:
    - python=3.6
    - flask
    - conda-forge::requests
```
https://github.com/conda/conda/issues/7202

We'd need to update the `_get_channels_packages` function and allow a fallback strategy in case the conda version is too old. 
https://github.com/kipoi/kipoi/blob/master/kipoi/components.py#L585-L597

- [ ] bellow which conda version such synthax doesn't work?
- [ ] test the installation of all the dependencies
