### ISSUE TITLE
URL downloader for the files

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#34]
Everywhere where the weights/model files are specified, support to specify the link

In `model.yaml`:
```yaml
    type: keras
    args:
      arch: http://.../link1
      weights: http://.../link2
```
Download paths (maps the argument names):
- arch url -> `arch.json`
- weights url -> `weights.h5`

## Questions

- [ ] how to deal with artifacts for the dataloaders?
   -  for the input arguments of the dataloader, we could specify whether we deliver the files with the dataloader

```yaml
arguments:
    fasta_file:
        descr: Reference genome sequence
        provided_as: dataloader_files/hg38.fa
    preproc_transformer:
        descr: path to the serialized tranformer used for pre-processing.
        provided_as: http:// ... /link2
```

Download those datasets as: 
```python
dl.args.fasta_file.download_default()
```
- [ ] type: file_path - emphasize that this is indeed a file instead of a string
