### ISSUE TITLE
Update docs for 'contributing multiple very similar models`

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#350]
Docs url: http://kipoi.org/docs/contributing/06_dumping_models_programatically/

Re-use the description from https://github.com/kipoi/kipoi/pull/349.

**Comment by Avsecz** [comment]
Example model group is here: https://github.com/kipoi/kipoi/tree/93819a8867fde2317215bf833982f3cb91bd0744/example/models/multiple_models

Each file gets contributed by specifying two files.

- **model-template.yaml**. May contain jinja2 placeholders 
```yaml
defined_as: model.MyModel
args:
  dummy_add: {{ dummy_add }}  # override

default_dataloader:
  defined_as: kipoiseq.datasets.SeqDataset
  default_args:
    auto_resize_len: 10

dependencies:
  pip:
    - kipoiseq

info:
  doc: {{ doc }}  # override

schema:
  inputs:
    shape: (10, 4)
    doc: sequence {{ var1 }}
  targets:
    shape: (None,)
    doc: prediction
```

- **models.tsv**. Needs to contain the `model` column and any other columns which will get used to populate `model-template.yaml` appropriately
```tsv
model	dummy_add	doc	var1
model1	1	"model returning one"	one
submodel/model2	2	"model returning two"	two
```

Optionally, also 
`dataloader-template.yaml` can be used. 

### Zenodo use-case

To contribute multiple models on zenodo, the best way is to have an `id` for each model and the files related to the model should contain the id:
- model-template.yaml
```yaml
defined_as: model.MyModel
args:
  weights: 
    url: http://zenodo..../{{ id }}.json
    md5: {{ weights_md5 }} 
  arch: 
    url: http://zenodo..../{{ id }}.h5
    md5: {{ arch_md5 }} 
```
- models.tsv
```tsv
model	id	weights_md5	arch_md5
...
```

## Usage
- Interface to the models says the same as if these models were arranged in the file-system hirearchy
