### ISSUE TITLE
Add option to config.yaml to opt-out from the automatic updates

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#362]
Currently, the repository is always checked for updates. We should have an `auto_pull` option (by default `True`) in model sources:

```yaml
model_sources:
  kipoi: # source name 
    type: git-lfs  # git repository with large file storage (lfs)
    remote_url: git@github.com:kipoi/models.git  # git remote
    local_path: /home/avsec/.kipoi/models/ # local storage path
    auto_pull: True  # or False
```
