### ISSUE TITLE
Model source - required kipoi version

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#363]
Allow the model source to specify the required kipoi version:
- display a warning if the kipoi version is not compliant and suggest to run `pip install -U kipoi`

add `requirements to `config.yaml`

https://github.com/kipoi/models/blob/master/config.yaml
```yaml
test:
  constraints:
    Basenji:
      batch_size: 2
requirements:
  - kipoi>=...
```
