### ISSUE TITLE
Improve the getting started templates

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#408]
Example: 
![image](https://user-images.githubusercontent.com/10011161/49333057-5f82df00-f5b8-11e8-98b6-62c1ff35840c.png)

Returns the following yaml: 

```yaml
defined_as: kipoi.model.KerasModel
args: # arguments of kipoi.model.KerasModel
    arch:
        url: https://zenodo.org/path/to/my/architecture/file
        md5: 1234567890abc
    weights:
        url: https://zenodo.org/path/to/my/model/weights.h5
        md5: 1234567890abc
default_dataloader: 
    defined_as: kipoiseq.dataloaders.SeqIntervalDl
    default_args: # Optional arguments to the SeqIntervalDl dataloader
        auto_resize_len: 1000 # Automatically resize sequence intervals
        alphabet_axis: 1 # dimension in which alphabet should be one-hot encoded, default: 1
        dummy_axis: 2 # Add a dummy axis. Omit in order not to create dummy_axis.
        alphabet: "ACGT" # Order of letters in 1-hot encoding
        ignore_targets: False # if True, dont return any target variables
        #dtype: float #defines the numpy dtype of the returned array. Example: int, np.int32, np.float32, float
info: # General information about the model
    authors: 
        - name: Your Name
          github: your_github_username
          email: your_email@host.org
    doc: Model predicting the Iris species
    cite_as: https://doi.org:/... # preferably a doi url to the paper
    trained_on: Iris species dataset (http://archive.ics.uci.edu/ml/datasets/Iris) # short dataset description
    license: MIT # Software License - if not set defaults to MIT
dependencies:
    conda: # install via conda
      - python=3.5
      - h5py
      # - soumith::pytorch  # specify packages from other channels via <channel>::<package>      
    pip:   # install via pip
      - keras>=2.0.4
      - tensorflow>=1.0
schema:  # Model schema. The schema defintion is essential for kipoi plug-ins to work.
    inputs:
        features:
            shape: (4,)  # array shape of a single sample (omitting the batch dimension)
            doc: "Features in cm: sepal length, sepal width, petal length, petal width."
    targets:
        shape: (3,)
        doc: "One-hot encoded array of classes: setosa, versicolor, virginica."
```

where the schema has nothing to do with the sequence-based model.
