### ISSUE TITLE
Add `example` to dataloader.yaml::args and deprecate test.json

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#47]
In `dataloader.py`, we should have:
```yaml
type: Dataset
defined_as: ...
args:
  arg1:
     descr: Path to the csv file
     example: example_files/arg1.csv
  arg2:
      descr: Path to the ... file
      example: example_files/arg2.csv
   arg2:
      descr: Some parameter
      example: 3
```

- rename `test_files` to `example_files`

This will deprecate writing the `test.json` files in `test_files/`. We can now always load the model with cwd in the same level as model's directory. All paths in the yaml file can be relative.

Additional functionality to Dataloader:
- `init_example()` - init the dataloader with `example` parameters
- update `Pipeline.predict_example` using `init_example`
