### ISSUE TITLE
yaml dependencies field: allow file path

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#52]
In addition to the normal `dependencies` field in the yaml file:

```yaml
dependencies:
    conda: # directly install via conda
      - python=2.7
      - scikit-learn
      # - conda-forge::spacy  # use a special channel via <channel>::<package>
    pip:
       - tqdm  # pip packages
```
allow for file path:

```yaml
dependencies:
    conda: conda_requirements.txt
    pip: pip_requirements.txt
```
