### ISSUE TITLE
Docker containers for kipoi

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#54]
## Use cases
- automatically build docker images for submitted models
- allow people to contribute docker images as models

The API could be `kipoi docker predict ...`

## Open questions

- [ ] how to conveniently mount the data inside the container?
  - [ ] the IBM released the docker containers for the recent DREAM challenge. Is there anything we can learn from there or from the DREAM pipelines?

## Automatically build docker images for submitted models

- [ ] is the `dependencies` field in mode/dataloader.yaml and all the other model files enough to build the container?

## Contribute docker images as models

Allow the contributors to just submit the docker container link in the yaml file

```yaml
type: docker
args:
  container: <dockerhub_username>/<model> ... 
```

This would contain the entire model pipeline. We can have the same thing in the dataloader.yaml
```yaml
type: docker
defined_as: <dockerhub_username>/<model> ... 
args:
  ...
```
