### ISSUE TITLE
Flexible InterpretationProvider abstract classess

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#59]
We should define various abstract classes for model postprocessing here: https://github.com/kipoi/kipoi/tree/master/kipoi/postprocessing

A user should implement various postprocessing classess (inheriting from specific classes in `kipoi.postprocessing...`) and list them under the `postprocessing` module in `model.yaml`:

```yaml
...
postprocessing:
  - type: interpretation
    args:
      interpretation_providers:
        - name: deeplift
          path: postprocessors.py::MyDeepliftGradientClass
          type: DeepLiftProvider
        - name: gradient
          path: postprocessors.py::ModelGradients
          type: ClassificationrGradientProvider
```
A cli would then look something like this:

```bash
kipoi interpret model --source=... --use=deeplift --kwargs={"foo": "bar"} --output=out.file
```
## Questions

- Which abstract classes do we need?
  - Which methods on the model do different interpretation methods require?
- What interpretation operations would a regular user want to perform with the model (+maybe new data)?
  - What would be the simplest CLI for that?
