### ISSUE TITLE
Fix model <-> dataloader compatibility tests

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#69]
BUG: allow different data structures with same names

i.e. if we have in `dataloader.py` an entry:

```yaml
output_schema:
  targets:
    out1:
      shape: ...
    out2:
      shape: ...
```

and in `model.py` the following entry:

```yaml
schema:
  targets:
    - name: out1
      shape: ...
    - name: out2
      shape: ...
```

This should still be accepted as long as the names are specified and they match.

Needs to be implemented here: https://github.com/kipoi/kipoi/blob/master/kipoi/components.py#L266
