### ISSUE TITLE
Allow for model parametrization in `__init__.py`

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#84]
Currently, the model doesn't accept any arguments from the command line. 

```yaml
type: custom
args:
  file: model.py
  object: HALModel
```

We should allow some attributes by:
```yaml
type: custom
load_args:
  file: model.py
  object: HALModel
args:
  arg1: 
    doc: ...
    default: ...
  arg2:
    doc: description2
    default: ...
```

and for the Keras model, it would look the same but without any args:
```yaml
type: keras
load_args:
    arch: model_files/model.json
    weights: model_files/weights.h5
```

### Dataloader

Correspondingly, we should change the dataloader.yaml args to be:

```yaml
type: Dataset
load_args:
  file: dataloader.py
  object: MyObject
```
 instead of 
```yaml
type: Dataset
defined_as: dataloader.py::MyObject
```
